// Code generated by protoc-gen-go. DO NOT EDIT.
// source: decision_response/decision_response.proto

package decision_response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModificationsType int32

const (
	ModificationsType_NULL          ModificationsType = 0
	ModificationsType_JSON          ModificationsType = 1
	ModificationsType_TEXT          ModificationsType = 2
	ModificationsType_IMAGE         ModificationsType = 3
	ModificationsType_HTML          ModificationsType = 4
	ModificationsType_FLAG          ModificationsType = 5
	ModificationsType_REDIRECT      ModificationsType = 6
	ModificationsType_TURING_ENGINE ModificationsType = 7
)

var ModificationsType_name = map[int32]string{
	0: "NULL",
	1: "JSON",
	2: "TEXT",
	3: "IMAGE",
	4: "HTML",
	5: "FLAG",
	6: "REDIRECT",
	7: "TURING_ENGINE",
}

var ModificationsType_value = map[string]int32{
	"NULL":          0,
	"JSON":          1,
	"TEXT":          2,
	"IMAGE":         3,
	"HTML":          4,
	"FLAG":          5,
	"REDIRECT":      6,
	"TURING_ENGINE": 7,
}

func (x ModificationsType) String() string {
	return proto.EnumName(ModificationsType_name, int32(x))
}

func (ModificationsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{0}
}

type CampaignIdVariationId struct {
	//*
	// campaign id
	//
	// Required
	//
	// The campaign id
	CampaignId string `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	//*
	// variation id
	//
	// Required
	//
	// The variation id
	VariationId          string   `protobuf:"bytes,2,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignIdVariationId) Reset()         { *m = CampaignIdVariationId{} }
func (m *CampaignIdVariationId) String() string { return proto.CompactTextString(m) }
func (*CampaignIdVariationId) ProtoMessage()    {}
func (*CampaignIdVariationId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{0}
}

func (m *CampaignIdVariationId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignIdVariationId.Unmarshal(m, b)
}
func (m *CampaignIdVariationId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignIdVariationId.Marshal(b, m, deterministic)
}
func (m *CampaignIdVariationId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignIdVariationId.Merge(m, src)
}
func (m *CampaignIdVariationId) XXX_Size() int {
	return xxx_messageInfo_CampaignIdVariationId.Size(m)
}
func (m *CampaignIdVariationId) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignIdVariationId.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignIdVariationId proto.InternalMessageInfo

func (m *CampaignIdVariationId) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *CampaignIdVariationId) GetVariationId() string {
	if m != nil {
		return m.VariationId
	}
	return ""
}

type Modifications struct {
	//*
	// modification type
	//
	// Required
	//
	// The type of the modification of the variation
	Type ModificationsType `protobuf:"varint,1,opt,name=type,proto3,enum=flagship.protobuf.ModificationsType" json:"type,omitempty"`
	//*
	// value
	//
	// Required
	//
	// The modifications value in json
	Value                *_struct.Struct `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Modifications) Reset()         { *m = Modifications{} }
func (m *Modifications) String() string { return proto.CompactTextString(m) }
func (*Modifications) ProtoMessage()    {}
func (*Modifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{1}
}

func (m *Modifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Modifications.Unmarshal(m, b)
}
func (m *Modifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Modifications.Marshal(b, m, deterministic)
}
func (m *Modifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Modifications.Merge(m, src)
}
func (m *Modifications) XXX_Size() int {
	return xxx_messageInfo_Modifications.Size(m)
}
func (m *Modifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Modifications.DiscardUnknown(m)
}

var xxx_messageInfo_Modifications proto.InternalMessageInfo

func (m *Modifications) GetType() ModificationsType {
	if m != nil {
		return m.Type
	}
	return ModificationsType_NULL
}

func (m *Modifications) GetValue() *_struct.Struct {
	if m != nil {
		return m.Value
	}
	return nil
}

type TuringEngineOptions struct {
	//*
	// Turing engine Context
	//
	// Required
	//
	// The context key(s) sent to turing engine
	ContextKeys          map[string]string `protobuf:"bytes,1,rep,name=context_keys,json=contextKeys,proto3" json:"context_keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TuringEngineOptions) Reset()         { *m = TuringEngineOptions{} }
func (m *TuringEngineOptions) String() string { return proto.CompactTextString(m) }
func (*TuringEngineOptions) ProtoMessage()    {}
func (*TuringEngineOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{2}
}

func (m *TuringEngineOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TuringEngineOptions.Unmarshal(m, b)
}
func (m *TuringEngineOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TuringEngineOptions.Marshal(b, m, deterministic)
}
func (m *TuringEngineOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TuringEngineOptions.Merge(m, src)
}
func (m *TuringEngineOptions) XXX_Size() int {
	return xxx_messageInfo_TuringEngineOptions.Size(m)
}
func (m *TuringEngineOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TuringEngineOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TuringEngineOptions proto.InternalMessageInfo

func (m *TuringEngineOptions) GetContextKeys() map[string]string {
	if m != nil {
		return m.ContextKeys
	}
	return nil
}

type Variation struct {
	//*
	// variation ID
	//
	// Required
	//
	// The ID of the variation the visitor is affected to
	Id *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// modifications
	//
	// Required
	//
	// The modifications field for the variation
	Modifications *Modifications `protobuf:"bytes,2,opt,name=modifications,proto3" json:"modifications,omitempty"`
	//*
	// is reference
	//
	// Optional
	//
	// True if variation is reference
	Reference            bool     `protobuf:"varint,3,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Variation) Reset()         { *m = Variation{} }
func (m *Variation) String() string { return proto.CompactTextString(m) }
func (*Variation) ProtoMessage()    {}
func (*Variation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{3}
}

func (m *Variation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variation.Unmarshal(m, b)
}
func (m *Variation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variation.Marshal(b, m, deterministic)
}
func (m *Variation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variation.Merge(m, src)
}
func (m *Variation) XXX_Size() int {
	return xxx_messageInfo_Variation.Size(m)
}
func (m *Variation) XXX_DiscardUnknown() {
	xxx_messageInfo_Variation.DiscardUnknown(m)
}

var xxx_messageInfo_Variation proto.InternalMessageInfo

func (m *Variation) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Variation) GetModifications() *Modifications {
	if m != nil {
		return m.Modifications
	}
	return nil
}

func (m *Variation) GetReference() bool {
	if m != nil {
		return m.Reference
	}
	return false
}

type FullVariation struct {
	//*
	// variation ID
	//
	// Required
	//
	// The ID of the variation the visitor is affected to
	Id *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// modifications
	//
	// Required
	//
	// The modifications field for the variation
	Modifications *Modifications `protobuf:"bytes,2,opt,name=modifications,proto3" json:"modifications,omitempty"`
	//*
	// Turing engine Options
	//
	// Optional
	//
	// The turing engine options
	TeOptions *TuringEngineOptions `protobuf:"bytes,3,opt,name=te_options,json=teOptions,proto3" json:"te_options,omitempty"`
	//*
	// Allocation
	//
	// Optional
	//
	// The allocation
	Allocation int32 `protobuf:"varint,4,opt,name=allocation,proto3" json:"allocation,omitempty"`
	//*
	// is reference
	//
	// Optional
	//
	// True if variation is reference
	Reference            bool     `protobuf:"varint,5,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullVariation) Reset()         { *m = FullVariation{} }
func (m *FullVariation) String() string { return proto.CompactTextString(m) }
func (*FullVariation) ProtoMessage()    {}
func (*FullVariation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{4}
}

func (m *FullVariation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullVariation.Unmarshal(m, b)
}
func (m *FullVariation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullVariation.Marshal(b, m, deterministic)
}
func (m *FullVariation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullVariation.Merge(m, src)
}
func (m *FullVariation) XXX_Size() int {
	return xxx_messageInfo_FullVariation.Size(m)
}
func (m *FullVariation) XXX_DiscardUnknown() {
	xxx_messageInfo_FullVariation.DiscardUnknown(m)
}

var xxx_messageInfo_FullVariation proto.InternalMessageInfo

func (m *FullVariation) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *FullVariation) GetModifications() *Modifications {
	if m != nil {
		return m.Modifications
	}
	return nil
}

func (m *FullVariation) GetTeOptions() *TuringEngineOptions {
	if m != nil {
		return m.TeOptions
	}
	return nil
}

func (m *FullVariation) GetAllocation() int32 {
	if m != nil {
		return m.Allocation
	}
	return 0
}

func (m *FullVariation) GetReference() bool {
	if m != nil {
		return m.Reference
	}
	return false
}

type Campaign struct {
	//*
	// campaign ID
	//
	// Required
	//
	// The ID of the campaign the visitor is affected to
	Id *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// variation group ID
	//
	// Required
	//
	// The ID of the variation group the visitor is affected to
	VariationGroupId *wrappers.StringValue `protobuf:"bytes,2,opt,name=variation_group_id,json=variationGroupId,proto3" json:"variation_group_id,omitempty"`
	//*
	// variation
	//
	// Required
	//
	// The variation info the visitor is affected to
	Variation            *Variation `protobuf:"bytes,3,opt,name=variation,proto3" json:"variation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{5}
}

func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (m *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(m, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Campaign) GetVariationGroupId() *wrappers.StringValue {
	if m != nil {
		return m.VariationGroupId
	}
	return nil
}

func (m *Campaign) GetVariation() *Variation {
	if m != nil {
		return m.Variation
	}
	return nil
}

type AccountSettings struct {
	//*
	// Experience continuity
	//
	// Required
	//
	// True if experience continuity is activated in account settings
	EnabledXPX *wrappers.BoolValue `protobuf:"bytes,1,opt,name=enabledXPX,proto3" json:"enabledXPX,omitempty"`
	//*
	// One visitor one test
	//
	// Required
	//
	// True if one visitor one test is activated in account settings
	Enabled1V1T          *wrappers.BoolValue `protobuf:"bytes,2,opt,name=enabled1V1T,proto3" json:"enabled1V1T,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AccountSettings) Reset()         { *m = AccountSettings{} }
func (m *AccountSettings) String() string { return proto.CompactTextString(m) }
func (*AccountSettings) ProtoMessage()    {}
func (*AccountSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{6}
}

func (m *AccountSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSettings.Unmarshal(m, b)
}
func (m *AccountSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSettings.Marshal(b, m, deterministic)
}
func (m *AccountSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSettings.Merge(m, src)
}
func (m *AccountSettings) XXX_Size() int {
	return xxx_messageInfo_AccountSettings.Size(m)
}
func (m *AccountSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSettings.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSettings proto.InternalMessageInfo

func (m *AccountSettings) GetEnabledXPX() *wrappers.BoolValue {
	if m != nil {
		return m.EnabledXPX
	}
	return nil
}

func (m *AccountSettings) GetEnabled1V1T() *wrappers.BoolValue {
	if m != nil {
		return m.Enabled1V1T
	}
	return nil
}

type DecisionResponse struct {
	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	VisitorId *wrappers.StringValue `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	//*
	// decision group
	//
	// Optional
	//
	// The custom visitor group
	Campaigns []*Campaign `protobuf:"bytes,2,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	//*
	// account settings
	//
	// Optional
	//
	// Account settings enabled and activated in the platform
	AccountSettings      *AccountSettings `protobuf:"bytes,3,opt,name=accountSettings,proto3" json:"accountSettings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DecisionResponse) Reset()         { *m = DecisionResponse{} }
func (m *DecisionResponse) String() string { return proto.CompactTextString(m) }
func (*DecisionResponse) ProtoMessage()    {}
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{7}
}

func (m *DecisionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecisionResponse.Unmarshal(m, b)
}
func (m *DecisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecisionResponse.Marshal(b, m, deterministic)
}
func (m *DecisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecisionResponse.Merge(m, src)
}
func (m *DecisionResponse) XXX_Size() int {
	return xxx_messageInfo_DecisionResponse.Size(m)
}
func (m *DecisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecisionResponse proto.InternalMessageInfo

func (m *DecisionResponse) GetVisitorId() *wrappers.StringValue {
	if m != nil {
		return m.VisitorId
	}
	return nil
}

func (m *DecisionResponse) GetCampaigns() []*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *DecisionResponse) GetAccountSettings() *AccountSettings {
	if m != nil {
		return m.AccountSettings
	}
	return nil
}

type DecisionResponsePanic struct {
	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	VisitorId *wrappers.StringValue `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	//*
	// decision group
	//
	// Optional
	//
	// The custom visitor group
	Campaigns []*Campaign `protobuf:"bytes,2,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	//*
	// panic
	//
	// Optional
	//
	// True if panic mode is set for the account environment
	Panic                bool     `protobuf:"varint,3,opt,name=panic,proto3" json:"panic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecisionResponsePanic) Reset()         { *m = DecisionResponsePanic{} }
func (m *DecisionResponsePanic) String() string { return proto.CompactTextString(m) }
func (*DecisionResponsePanic) ProtoMessage()    {}
func (*DecisionResponsePanic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{8}
}

func (m *DecisionResponsePanic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecisionResponsePanic.Unmarshal(m, b)
}
func (m *DecisionResponsePanic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecisionResponsePanic.Marshal(b, m, deterministic)
}
func (m *DecisionResponsePanic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecisionResponsePanic.Merge(m, src)
}
func (m *DecisionResponsePanic) XXX_Size() int {
	return xxx_messageInfo_DecisionResponsePanic.Size(m)
}
func (m *DecisionResponsePanic) XXX_DiscardUnknown() {
	xxx_messageInfo_DecisionResponsePanic.DiscardUnknown(m)
}

var xxx_messageInfo_DecisionResponsePanic proto.InternalMessageInfo

func (m *DecisionResponsePanic) GetVisitorId() *wrappers.StringValue {
	if m != nil {
		return m.VisitorId
	}
	return nil
}

func (m *DecisionResponsePanic) GetCampaigns() []*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *DecisionResponsePanic) GetPanic() bool {
	if m != nil {
		return m.Panic
	}
	return false
}

type DecisionResponseFull struct {
	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	VisitorId *wrappers.StringValue `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	//*
	// decision group
	//
	// Optional
	//
	// The custom visitor group
	Campaigns []*Campaign `protobuf:"bytes,2,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	//*
	// campaigns_variation
	//
	// Optional
	//
	// An array of all the campaign and associated variation id
	CampaignsVariation []*CampaignIdVariationId `protobuf:"bytes,3,rep,name=campaigns_variation,json=campaignsVariation,proto3" json:"campaigns_variation,omitempty"`
	//*
	// merged_modifications
	//
	// Optional
	//
	// The merged modifications for all the campaigns
	MergedModifications *_struct.Struct `protobuf:"bytes,4,opt,name=merged_modifications,json=mergedModifications,proto3" json:"merged_modifications,omitempty"`
	//*
	// panic
	//
	// Optional
	//
	// True if panic mode is set for the account environment
	Panic                bool     `protobuf:"varint,5,opt,name=panic,proto3" json:"panic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecisionResponseFull) Reset()         { *m = DecisionResponseFull{} }
func (m *DecisionResponseFull) String() string { return proto.CompactTextString(m) }
func (*DecisionResponseFull) ProtoMessage()    {}
func (*DecisionResponseFull) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{9}
}

func (m *DecisionResponseFull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecisionResponseFull.Unmarshal(m, b)
}
func (m *DecisionResponseFull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecisionResponseFull.Marshal(b, m, deterministic)
}
func (m *DecisionResponseFull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecisionResponseFull.Merge(m, src)
}
func (m *DecisionResponseFull) XXX_Size() int {
	return xxx_messageInfo_DecisionResponseFull.Size(m)
}
func (m *DecisionResponseFull) XXX_DiscardUnknown() {
	xxx_messageInfo_DecisionResponseFull.DiscardUnknown(m)
}

var xxx_messageInfo_DecisionResponseFull proto.InternalMessageInfo

func (m *DecisionResponseFull) GetVisitorId() *wrappers.StringValue {
	if m != nil {
		return m.VisitorId
	}
	return nil
}

func (m *DecisionResponseFull) GetCampaigns() []*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *DecisionResponseFull) GetCampaignsVariation() []*CampaignIdVariationId {
	if m != nil {
		return m.CampaignsVariation
	}
	return nil
}

func (m *DecisionResponseFull) GetMergedModifications() *_struct.Struct {
	if m != nil {
		return m.MergedModifications
	}
	return nil
}

func (m *DecisionResponseFull) GetPanic() bool {
	if m != nil {
		return m.Panic
	}
	return false
}

type DecisionResponseSimple struct {
	//*
	// campaigns_variation
	//
	// Optional
	//
	// An array of all the campaign and associated variation id
	CampaignsVariation []*CampaignIdVariationId `protobuf:"bytes,1,rep,name=campaigns_variation,json=campaignsVariation,proto3" json:"campaigns_variation,omitempty"`
	//*
	// merged_modifications
	//
	// Optional
	//
	// The merged modifications for all the campaigns
	MergedModifications  *_struct.Struct `protobuf:"bytes,2,opt,name=merged_modifications,json=mergedModifications,proto3" json:"merged_modifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DecisionResponseSimple) Reset()         { *m = DecisionResponseSimple{} }
func (m *DecisionResponseSimple) String() string { return proto.CompactTextString(m) }
func (*DecisionResponseSimple) ProtoMessage()    {}
func (*DecisionResponseSimple) Descriptor() ([]byte, []int) {
	return fileDescriptor_f38fa95d86323f29, []int{10}
}

func (m *DecisionResponseSimple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecisionResponseSimple.Unmarshal(m, b)
}
func (m *DecisionResponseSimple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecisionResponseSimple.Marshal(b, m, deterministic)
}
func (m *DecisionResponseSimple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecisionResponseSimple.Merge(m, src)
}
func (m *DecisionResponseSimple) XXX_Size() int {
	return xxx_messageInfo_DecisionResponseSimple.Size(m)
}
func (m *DecisionResponseSimple) XXX_DiscardUnknown() {
	xxx_messageInfo_DecisionResponseSimple.DiscardUnknown(m)
}

var xxx_messageInfo_DecisionResponseSimple proto.InternalMessageInfo

func (m *DecisionResponseSimple) GetCampaignsVariation() []*CampaignIdVariationId {
	if m != nil {
		return m.CampaignsVariation
	}
	return nil
}

func (m *DecisionResponseSimple) GetMergedModifications() *_struct.Struct {
	if m != nil {
		return m.MergedModifications
	}
	return nil
}

func init() {
	proto.RegisterEnum("flagship.protobuf.ModificationsType", ModificationsType_name, ModificationsType_value)
	proto.RegisterType((*CampaignIdVariationId)(nil), "flagship.protobuf.CampaignIdVariationId")
	proto.RegisterType((*Modifications)(nil), "flagship.protobuf.Modifications")
	proto.RegisterType((*TuringEngineOptions)(nil), "flagship.protobuf.TuringEngineOptions")
	proto.RegisterMapType((map[string]string)(nil), "flagship.protobuf.TuringEngineOptions.ContextKeysEntry")
	proto.RegisterType((*Variation)(nil), "flagship.protobuf.Variation")
	proto.RegisterType((*FullVariation)(nil), "flagship.protobuf.FullVariation")
	proto.RegisterType((*Campaign)(nil), "flagship.protobuf.Campaign")
	proto.RegisterType((*AccountSettings)(nil), "flagship.protobuf.AccountSettings")
	proto.RegisterType((*DecisionResponse)(nil), "flagship.protobuf.DecisionResponse")
	proto.RegisterType((*DecisionResponsePanic)(nil), "flagship.protobuf.DecisionResponsePanic")
	proto.RegisterType((*DecisionResponseFull)(nil), "flagship.protobuf.DecisionResponseFull")
	proto.RegisterType((*DecisionResponseSimple)(nil), "flagship.protobuf.DecisionResponseSimple")
}

func init() {
	proto.RegisterFile("decision_response/decision_response.proto", fileDescriptor_f38fa95d86323f29)
}

var fileDescriptor_f38fa95d86323f29 = []byte{
	// 818 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x18, 0xc5, 0xde, 0xa4, 0xc4, 0x9f, 0x37, 0xd4, 0x3b, 0x9b, 0x42, 0x14, 0xa2, 0x12, 0x2c, 0x84,
	0x02, 0xa2, 0x89, 0x1a, 0x2e, 0xda, 0x2e, 0x08, 0x69, 0xbb, 0xf5, 0x06, 0x2f, 0xd9, 0xb4, 0x9a,
	0xb8, 0xab, 0xa5, 0x5c, 0x58, 0x8e, 0x3d, 0x71, 0x47, 0x75, 0x3c, 0xc6, 0x3f, 0xa1, 0x79, 0x05,
	0x78, 0x08, 0xae, 0x78, 0x00, 0x9e, 0x00, 0xee, 0x79, 0x01, 0x1e, 0x07, 0xf9, 0x27, 0x76, 0xe2,
	0x84, 0x6d, 0xf7, 0xa2, 0xda, 0xbb, 0x99, 0x6f, 0xce, 0xf9, 0x72, 0xce, 0x19, 0xcf, 0x4c, 0xe0,
	0x0b, 0x8b, 0x98, 0x34, 0xa0, 0xcc, 0xd5, 0x7d, 0x12, 0x78, 0xcc, 0x0d, 0x48, 0x7f, 0xab, 0xd2,
	0xf3, 0x7c, 0x16, 0x32, 0x74, 0x30, 0x73, 0x0c, 0x3b, 0x78, 0x49, 0xbd, 0x74, 0x3e, 0x8d, 0x66,
	0xad, 0xbb, 0x36, 0x63, 0xb6, 0x43, 0xfa, 0xab, 0x42, 0xff, 0x17, 0xdf, 0xf0, 0x3c, 0xe2, 0x07,
	0x29, 0xa4, 0xd5, 0x2e, 0xaf, 0x07, 0xa1, 0x1f, 0x99, 0x61, 0xba, 0x2a, 0xff, 0x04, 0x77, 0x4e,
	0x8c, 0xb9, 0x67, 0x50, 0xdb, 0x55, 0xad, 0x0b, 0xc3, 0xa7, 0x46, 0x48, 0x99, 0xab, 0x5a, 0xe8,
	0x13, 0x10, 0xcd, 0x6c, 0x41, 0xa7, 0x56, 0x93, 0xeb, 0x70, 0x5d, 0x01, 0x83, 0x99, 0x63, 0xd1,
	0xa7, 0xb0, 0xbf, 0x58, 0xe1, 0x63, 0x04, 0x9f, 0x20, 0xc4, 0x45, 0xd1, 0x43, 0x7e, 0x0d, 0xf5,
	0x73, 0x66, 0xd1, 0x19, 0x35, 0x93, 0x4a, 0x80, 0x1e, 0x42, 0x25, 0x5c, 0x7a, 0x24, 0xe9, 0xf6,
	0xc1, 0xe0, 0xb3, 0xde, 0x96, 0x9b, 0xde, 0x06, 0x5e, 0x5b, 0x7a, 0x04, 0x27, 0x0c, 0x74, 0x0f,
	0xaa, 0x0b, 0xc3, 0x89, 0x48, 0xf2, 0x33, 0xe2, 0xe0, 0xa3, 0x5e, 0xea, 0xaa, 0x20, 0x4e, 0x12,
	0x57, 0x38, 0x45, 0xc9, 0x7f, 0x72, 0x70, 0xa8, 0x45, 0x3e, 0x75, 0x6d, 0xc5, 0xb5, 0xa9, 0x4b,
	0x9e, 0x7a, 0xa9, 0x80, 0x17, 0xb0, 0x6f, 0x32, 0x37, 0x24, 0xaf, 0x43, 0xfd, 0x15, 0x59, 0x06,
	0x4d, 0xae, 0xb3, 0xd7, 0x15, 0x07, 0x0f, 0x76, 0x08, 0xd9, 0xc1, 0xee, 0x9d, 0xa4, 0xd4, 0x1f,
	0xc8, 0x32, 0x50, 0xdc, 0xd0, 0x5f, 0x62, 0xd1, 0x2c, 0x2a, 0xad, 0xef, 0x40, 0x2a, 0x03, 0x90,
	0x04, 0x7b, 0xaf, 0xc8, 0x32, 0x4b, 0x2f, 0x1e, 0xa2, 0xc6, 0xba, 0x11, 0x21, 0xd3, 0x7b, 0xc4,
	0x3f, 0xe4, 0xe4, 0xdf, 0x39, 0x10, 0xf2, 0x1d, 0x40, 0x5f, 0x01, 0x9f, 0xc5, 0x2e, 0x0e, 0xda,
	0xbb, 0xdc, 0x52, 0xd7, 0xbe, 0x88, 0xb9, 0x98, 0xa7, 0x16, 0x3a, 0x85, 0xfa, 0x7c, 0x3d, 0xb9,
	0x2c, 0xa6, 0xce, 0x9b, 0x12, 0xc6, 0x9b, 0x34, 0xd4, 0x06, 0xc1, 0x27, 0x33, 0xe2, 0x13, 0xd7,
	0x24, 0xcd, 0xbd, 0x0e, 0xd7, 0xad, 0xe1, 0xa2, 0x20, 0xff, 0xca, 0x43, 0xfd, 0x34, 0x72, 0x9c,
	0x9b, 0x56, 0xa9, 0x00, 0x84, 0x44, 0x67, 0xe9, 0xae, 0x24, 0x32, 0xc5, 0xc1, 0xe7, 0x6f, 0xb7,
	0x87, 0x58, 0x08, 0xf3, 0x8f, 0xe1, 0x2e, 0x80, 0xe1, 0x38, 0x2c, 0xed, 0xda, 0xac, 0x74, 0xb8,
	0x6e, 0x15, 0xaf, 0x55, 0x36, 0xc3, 0xa8, 0x96, 0xc3, 0xf8, 0x9b, 0x83, 0xda, 0xea, 0xe8, 0x5c,
	0x33, 0x87, 0x33, 0x40, 0xc5, 0xd1, 0xb1, 0x7d, 0x16, 0x79, 0xab, 0x03, 0xf4, 0x26, 0xb6, 0x94,
	0xf3, 0x86, 0x31, 0x4d, 0xb5, 0xd0, 0x11, 0x08, 0x79, 0x2d, 0x8b, 0xa2, 0xbd, 0x23, 0x8a, 0x7c,
	0xcb, 0x70, 0x01, 0x97, 0x7f, 0xe3, 0xe0, 0xf6, 0xb1, 0x69, 0xb2, 0xc8, 0x0d, 0x27, 0x24, 0x0c,
	0xa9, 0x6b, 0x07, 0xe8, 0x08, 0x80, 0xb8, 0xc6, 0xd4, 0x21, 0xd6, 0xe5, 0xb3, 0xcb, 0xcc, 0x51,
	0x6b, 0x4b, 0xd3, 0x63, 0xc6, 0x9c, 0x54, 0xd1, 0x1a, 0x1a, 0x7d, 0x0b, 0x62, 0x36, 0xbb, 0x7f,
	0x71, 0x5f, 0xcb, 0x0c, 0x5d, 0x45, 0x5e, 0x87, 0xcb, 0xff, 0x72, 0x20, 0x3d, 0xc9, 0xee, 0x3d,
	0x9c, 0x5d, 0x7b, 0xe8, 0x1b, 0x80, 0x05, 0x0d, 0x68, 0xc8, 0x7c, 0xfd, 0x2d, 0x03, 0x16, 0x32,
	0xbc, 0x6a, 0xa1, 0x47, 0x20, 0xac, 0x2e, 0xac, 0xf8, 0x5b, 0x8b, 0x8f, 0xfa, 0xc7, 0x3b, 0xb2,
	0x59, 0xed, 0x22, 0x2e, 0xd0, 0x68, 0x04, 0xb7, 0x8d, 0xcd, 0x64, 0xb2, 0x70, 0xe5, 0x1d, 0x0d,
	0x4a, 0x19, 0xe2, 0x32, 0x55, 0xfe, 0x83, 0x83, 0x3b, 0x65, 0x6b, 0xcf, 0x0c, 0x97, 0x9a, 0x37,
	0xe6, 0xaf, 0x01, 0x55, 0x2f, 0x16, 0x90, 0x1d, 0xf2, 0x74, 0x22, 0xff, 0xc3, 0x43, 0xa3, 0xac,
	0x33, 0x3e, 0xf0, 0x37, 0x26, 0xf3, 0x47, 0x38, 0xcc, 0x27, 0xfa, 0xfa, 0x77, 0x1e, 0x37, 0xe9,
	0x5e, 0xd1, 0x64, 0xe3, 0x31, 0xc3, 0x28, 0x6f, 0x52, 0x5c, 0x5d, 0x67, 0xd0, 0x98, 0x13, 0xdf,
	0x26, 0x96, 0xbe, 0x79, 0x27, 0x55, 0xae, 0x7e, 0x60, 0x0e, 0x53, 0xd2, 0xe6, 0xbb, 0x96, 0xa7,
	0x59, 0x5d, 0x4f, 0xf3, 0x2f, 0x0e, 0x3e, 0x2c, 0xa7, 0x39, 0xa1, 0x73, 0xcf, 0x21, 0xff, 0xe7,
	0x8b, 0x7b, 0x87, 0xbe, 0xf8, 0xeb, 0xfb, 0xfa, 0xf2, 0x67, 0x38, 0xd8, 0x7a, 0x90, 0x51, 0x0d,
	0x2a, 0xe3, 0xe7, 0xa3, 0x91, 0xf4, 0x5e, 0x3c, 0x3a, 0x9b, 0x3c, 0x1d, 0x4b, 0x5c, 0x3c, 0xd2,
	0x94, 0x4b, 0x4d, 0xe2, 0x91, 0x00, 0x55, 0xf5, 0xfc, 0x78, 0xa8, 0x48, 0x7b, 0x71, 0xf1, 0x7b,
	0xed, 0x7c, 0x24, 0x55, 0xe2, 0xd1, 0xe9, 0xe8, 0x78, 0x28, 0x55, 0xd1, 0x3e, 0xd4, 0xb0, 0xf2,
	0x44, 0xc5, 0xca, 0x89, 0x26, 0xdd, 0x42, 0x07, 0x50, 0xd7, 0x9e, 0x63, 0x75, 0x3c, 0xd4, 0x95,
	0xf1, 0x50, 0x1d, 0x2b, 0xd2, 0xfb, 0x8f, 0x1f, 0xbd, 0x78, 0x60, 0xd3, 0xf0, 0x65, 0x34, 0xed,
	0x99, 0x6c, 0xde, 0x5f, 0x05, 0x71, 0x8f, 0xb2, 0x62, 0x9c, 0x48, 0xdf, 0xfe, 0x8b, 0x34, 0xbd,
	0x95, 0x2c, 0x7c, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xa0, 0xdc, 0x19, 0x50, 0x09,
	0x00, 0x00,
}
