// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.15.8
// source: decision_response/decision_response.proto

package decision_response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModificationsType int32

const (
	ModificationsType_NULL          ModificationsType = 0
	ModificationsType_JSON          ModificationsType = 1
	ModificationsType_TEXT          ModificationsType = 2
	ModificationsType_IMAGE         ModificationsType = 3
	ModificationsType_HTML          ModificationsType = 4
	ModificationsType_FLAG          ModificationsType = 5
	ModificationsType_REDIRECT      ModificationsType = 6
	ModificationsType_TURING_ENGINE ModificationsType = 7
)

// Enum value maps for ModificationsType.
var (
	ModificationsType_name = map[int32]string{
		0: "NULL",
		1: "JSON",
		2: "TEXT",
		3: "IMAGE",
		4: "HTML",
		5: "FLAG",
		6: "REDIRECT",
		7: "TURING_ENGINE",
	}
	ModificationsType_value = map[string]int32{
		"NULL":          0,
		"JSON":          1,
		"TEXT":          2,
		"IMAGE":         3,
		"HTML":          4,
		"FLAG":          5,
		"REDIRECT":      6,
		"TURING_ENGINE": 7,
	}
)

func (x ModificationsType) Enum() *ModificationsType {
	p := new(ModificationsType)
	*p = x
	return p
}

func (x ModificationsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModificationsType) Descriptor() protoreflect.EnumDescriptor {
	return file_decision_response_decision_response_proto_enumTypes[0].Descriptor()
}

func (ModificationsType) Type() protoreflect.EnumType {
	return &file_decision_response_decision_response_proto_enumTypes[0]
}

func (x ModificationsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModificationsType.Descriptor instead.
func (ModificationsType) EnumDescriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{0}
}

type CampaignIdVariationId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// campaign id
	//
	// Required
	//
	// The campaign id
	CampaignId string `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	//*
	// variation id
	//
	// Required
	//
	// The variation id
	VariationId string `protobuf:"bytes,2,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
}

func (x *CampaignIdVariationId) Reset() {
	*x = CampaignIdVariationId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CampaignIdVariationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignIdVariationId) ProtoMessage() {}

func (x *CampaignIdVariationId) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignIdVariationId.ProtoReflect.Descriptor instead.
func (*CampaignIdVariationId) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{0}
}

func (x *CampaignIdVariationId) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignIdVariationId) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

type Modifications struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// modification type
	//
	// Required
	//
	// The type of the modification of the variation
	Type ModificationsType `protobuf:"varint,1,opt,name=type,proto3,enum=flagship.protobuf.ModificationsType" json:"type,omitempty"`
	//*
	// value
	//
	// Required
	//
	// The modifications value in json
	Value *structpb.Struct `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Modifications) Reset() {
	*x = Modifications{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Modifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Modifications) ProtoMessage() {}

func (x *Modifications) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Modifications.ProtoReflect.Descriptor instead.
func (*Modifications) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{1}
}

func (x *Modifications) GetType() ModificationsType {
	if x != nil {
		return x.Type
	}
	return ModificationsType_NULL
}

func (x *Modifications) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type TuringEngineOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Turing engine Context
	//
	// Required
	//
	// The context key(s) sent to turing engine
	ContextKeys map[string]string `protobuf:"bytes,1,rep,name=context_keys,json=contextKeys,proto3" json:"context_keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TuringEngineOptions) Reset() {
	*x = TuringEngineOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TuringEngineOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuringEngineOptions) ProtoMessage() {}

func (x *TuringEngineOptions) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuringEngineOptions.ProtoReflect.Descriptor instead.
func (*TuringEngineOptions) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{2}
}

func (x *TuringEngineOptions) GetContextKeys() map[string]string {
	if x != nil {
		return x.ContextKeys
	}
	return nil
}

type Variation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// variation ID
	//
	// Required
	//
	// The ID of the variation the visitor is affected to
	Id *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// modifications
	//
	// Required
	//
	// The modifications field for the variation
	Modifications *Modifications `protobuf:"bytes,2,opt,name=modifications,proto3" json:"modifications,omitempty"`
	//*
	// is reference
	//
	// Optional
	//
	// True if variation is reference
	Reference bool `protobuf:"varint,3,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *Variation) Reset() {
	*x = Variation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Variation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variation) ProtoMessage() {}

func (x *Variation) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variation.ProtoReflect.Descriptor instead.
func (*Variation) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{3}
}

func (x *Variation) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Variation) GetModifications() *Modifications {
	if x != nil {
		return x.Modifications
	}
	return nil
}

func (x *Variation) GetReference() bool {
	if x != nil {
		return x.Reference
	}
	return false
}

type FullVariation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// variation ID
	//
	// Required
	//
	// The ID of the variation the visitor is affected to
	Id *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// modifications
	//
	// Required
	//
	// The modifications field for the variation
	Modifications *Modifications `protobuf:"bytes,2,opt,name=modifications,proto3" json:"modifications,omitempty"`
	//*
	// Turing engine Options
	//
	// Optional
	//
	// The turing engine options
	TeOptions *TuringEngineOptions `protobuf:"bytes,3,opt,name=te_options,json=teOptions,proto3" json:"te_options,omitempty"`
	//*
	// Allocation
	//
	// Optional
	//
	// The allocation
	Allocation int32 `protobuf:"varint,4,opt,name=allocation,proto3" json:"allocation,omitempty"`
	//*
	// is reference
	//
	// Optional
	//
	// True if variation is reference
	Reference bool `protobuf:"varint,5,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *FullVariation) Reset() {
	*x = FullVariation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullVariation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullVariation) ProtoMessage() {}

func (x *FullVariation) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullVariation.ProtoReflect.Descriptor instead.
func (*FullVariation) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{4}
}

func (x *FullVariation) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FullVariation) GetModifications() *Modifications {
	if x != nil {
		return x.Modifications
	}
	return nil
}

func (x *FullVariation) GetTeOptions() *TuringEngineOptions {
	if x != nil {
		return x.TeOptions
	}
	return nil
}

func (x *FullVariation) GetAllocation() int32 {
	if x != nil {
		return x.Allocation
	}
	return 0
}

func (x *FullVariation) GetReference() bool {
	if x != nil {
		return x.Reference
	}
	return false
}

type Campaign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// campaign ID
	//
	// Required
	//
	// The ID of the campaign the visitor is affected to
	Id *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// variation group ID
	//
	// Required
	//
	// The ID of the variation group the visitor is affected to
	VariationGroupId *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=variation_group_id,json=variationGroupId,proto3" json:"variation_group_id,omitempty"`
	//*
	// variation
	//
	// Required
	//
	// The variation info the visitor is affected to
	Variation *Variation `protobuf:"bytes,3,opt,name=variation,proto3" json:"variation,omitempty"`
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{5}
}

func (x *Campaign) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Campaign) GetVariationGroupId() *wrapperspb.StringValue {
	if x != nil {
		return x.VariationGroupId
	}
	return nil
}

func (x *Campaign) GetVariation() *Variation {
	if x != nil {
		return x.Variation
	}
	return nil
}

type AccountSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Experience continuity
	//
	// Required
	//
	// True if experience continuity is activated in account settings
	EnabledXPX bool `protobuf:"varint,1,opt,name=enabledXPX,proto3" json:"enabledXPX,omitempty"`
	//*
	// One visitor one test
	//
	// Required
	//
	// True if one visitor one test is activated in account settings
	Enabled1V1T bool `protobuf:"varint,2,opt,name=enabled1V1T,proto3" json:"enabled1V1T,omitempty"`
}

func (x *AccountSettings) Reset() {
	*x = AccountSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSettings) ProtoMessage() {}

func (x *AccountSettings) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSettings.ProtoReflect.Descriptor instead.
func (*AccountSettings) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{6}
}

func (x *AccountSettings) GetEnabledXPX() bool {
	if x != nil {
		return x.EnabledXPX
	}
	return false
}

func (x *AccountSettings) GetEnabled1V1T() bool {
	if x != nil {
		return x.Enabled1V1T
	}
	return false
}

type DecisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	VisitorId *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	//*
	// decision group
	//
	// Optional
	//
	// The custom visitor group
	Campaigns []*Campaign `protobuf:"bytes,2,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	//*
	// account settings
	//
	// Optional
	//
	// Account settings enabled and activated in the platform
	AccountSettings *AccountSettings `protobuf:"bytes,3,opt,name=accountSettings,proto3" json:"accountSettings,omitempty"`
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{7}
}

func (x *DecisionResponse) GetVisitorId() *wrapperspb.StringValue {
	if x != nil {
		return x.VisitorId
	}
	return nil
}

func (x *DecisionResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *DecisionResponse) GetAccountSettings() *AccountSettings {
	if x != nil {
		return x.AccountSettings
	}
	return nil
}

type DecisionResponsePanic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	VisitorId *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	//*
	// decision group
	//
	// Optional
	//
	// The custom visitor group
	Campaigns []*Campaign `protobuf:"bytes,2,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	//*
	// panic
	//
	// Optional
	//
	// True if panic mode is set for the account environment
	Panic bool `protobuf:"varint,3,opt,name=panic,proto3" json:"panic,omitempty"`
}

func (x *DecisionResponsePanic) Reset() {
	*x = DecisionResponsePanic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionResponsePanic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponsePanic) ProtoMessage() {}

func (x *DecisionResponsePanic) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponsePanic.ProtoReflect.Descriptor instead.
func (*DecisionResponsePanic) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{8}
}

func (x *DecisionResponsePanic) GetVisitorId() *wrapperspb.StringValue {
	if x != nil {
		return x.VisitorId
	}
	return nil
}

func (x *DecisionResponsePanic) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *DecisionResponsePanic) GetPanic() bool {
	if x != nil {
		return x.Panic
	}
	return false
}

type DecisionResponseFull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	VisitorId *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	//*
	// decision group
	//
	// Optional
	//
	// The custom visitor group
	Campaigns []*Campaign `protobuf:"bytes,2,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	//*
	// campaigns_variation
	//
	// Optional
	//
	// An array of all the campaign and associated variation id
	CampaignsVariation []*CampaignIdVariationId `protobuf:"bytes,3,rep,name=campaigns_variation,json=campaignsVariation,proto3" json:"campaigns_variation,omitempty"`
	//*
	// merged_modifications
	//
	// Optional
	//
	// The merged modifications for all the campaigns
	MergedModifications *structpb.Struct `protobuf:"bytes,4,opt,name=merged_modifications,json=mergedModifications,proto3" json:"merged_modifications,omitempty"`
	//*
	// panic
	//
	// Optional
	//
	// True if panic mode is set for the account environment
	Panic bool `protobuf:"varint,5,opt,name=panic,proto3" json:"panic,omitempty"`
}

func (x *DecisionResponseFull) Reset() {
	*x = DecisionResponseFull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionResponseFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponseFull) ProtoMessage() {}

func (x *DecisionResponseFull) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponseFull.ProtoReflect.Descriptor instead.
func (*DecisionResponseFull) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{9}
}

func (x *DecisionResponseFull) GetVisitorId() *wrapperspb.StringValue {
	if x != nil {
		return x.VisitorId
	}
	return nil
}

func (x *DecisionResponseFull) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *DecisionResponseFull) GetCampaignsVariation() []*CampaignIdVariationId {
	if x != nil {
		return x.CampaignsVariation
	}
	return nil
}

func (x *DecisionResponseFull) GetMergedModifications() *structpb.Struct {
	if x != nil {
		return x.MergedModifications
	}
	return nil
}

func (x *DecisionResponseFull) GetPanic() bool {
	if x != nil {
		return x.Panic
	}
	return false
}

type DecisionResponseSimple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// campaigns_variation
	//
	// Optional
	//
	// An array of all the campaign and associated variation id
	CampaignsVariation []*CampaignIdVariationId `protobuf:"bytes,1,rep,name=campaigns_variation,json=campaignsVariation,proto3" json:"campaigns_variation,omitempty"`
	//*
	// merged_modifications
	//
	// Optional
	//
	// The merged modifications for all the campaigns
	MergedModifications *structpb.Struct `protobuf:"bytes,2,opt,name=merged_modifications,json=mergedModifications,proto3" json:"merged_modifications,omitempty"`
}

func (x *DecisionResponseSimple) Reset() {
	*x = DecisionResponseSimple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decision_response_decision_response_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionResponseSimple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponseSimple) ProtoMessage() {}

func (x *DecisionResponseSimple) ProtoReflect() protoreflect.Message {
	mi := &file_decision_response_decision_response_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponseSimple.ProtoReflect.Descriptor instead.
func (*DecisionResponseSimple) Descriptor() ([]byte, []int) {
	return file_decision_response_decision_response_proto_rawDescGZIP(), []int{10}
}

func (x *DecisionResponseSimple) GetCampaignsVariation() []*CampaignIdVariationId {
	if x != nil {
		return x.CampaignsVariation
	}
	return nil
}

func (x *DecisionResponseSimple) GetMergedModifications() *structpb.Struct {
	if x != nil {
		return x.MergedModifications
	}
	return nil
}

var File_decision_response_decision_response_proto protoreflect.FileDescriptor

var file_decision_response_decision_response_proto_rawDesc = []byte{
	0x0a, 0x29, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2f, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x15,
	0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x0d, 0x4d, 0x6f, 0x64,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x64,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x13, 0x54, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x45, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x5a, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x37, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x4b, 0x65, 0x79, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x9f, 0x01, 0x0a, 0x09, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x6d, 0x6f,
	0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x8a, 0x02, 0x0a, 0x0d, 0x46, 0x75,
	0x6c, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x0d, 0x6d, 0x6f, 0x64,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x0d, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x45, 0x0a, 0x0a, 0x74, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x75, 0x72, 0x69, 0x6e, 0x67,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x74,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xc0, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x12, 0x2c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x4a, 0x0a, 0x12, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x10, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x3a, 0x0a,
	0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x0f, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x58, 0x50, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x58, 0x50, 0x58, 0x12, 0x20, 0x0a, 0x0b,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x31, 0x56, 0x31, 0x54, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x31, 0x56, 0x31, 0x54, 0x22, 0xd8,
	0x01, 0x0a, 0x10, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x39, 0x0a, 0x09, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e,
	0x52, 0x09, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x12, 0x4c, 0x0a, 0x0f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xa5, 0x01, 0x0a, 0x15, 0x44, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61,
	0x6e, 0x69, 0x63, 0x12, 0x3b, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x39, 0x0a, 0x09, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e,
	0x52, 0x09, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x61, 0x6e, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x70, 0x61, 0x6e, 0x69,
	0x63, 0x22, 0xcb, 0x02, 0x0a, 0x14, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x3b, 0x0a, 0x0a, 0x76, 0x69,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x76, 0x69,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x09, 0x63, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43,
	0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x09, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67,
	0x6e, 0x73, 0x12, 0x59, 0x0a, 0x13, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x5f,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x12, 0x63, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x73, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a,
	0x14, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x13, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x6e,
	0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x70, 0x61, 0x6e, 0x69, 0x63, 0x22,
	0xbf, 0x01, 0x0a, 0x16, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x59, 0x0a, 0x13, 0x63, 0x61,
	0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68,
	0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x52, 0x12, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x14, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x5f,
	0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x13, 0x6d, 0x65,
	0x72, 0x67, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2a, 0x71, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45,
	0x58, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x54, 0x4d, 0x4c, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x4c, 0x41,
	0x47, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x10,
	0x06, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x55, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x45, 0x4e, 0x47, 0x49,
	0x4e, 0x45, 0x10, 0x07, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2d, 0x69, 0x6f, 0x2f, 0x66,
	0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_decision_response_decision_response_proto_rawDescOnce sync.Once
	file_decision_response_decision_response_proto_rawDescData = file_decision_response_decision_response_proto_rawDesc
)

func file_decision_response_decision_response_proto_rawDescGZIP() []byte {
	file_decision_response_decision_response_proto_rawDescOnce.Do(func() {
		file_decision_response_decision_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_decision_response_decision_response_proto_rawDescData)
	})
	return file_decision_response_decision_response_proto_rawDescData
}

var file_decision_response_decision_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_decision_response_decision_response_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_decision_response_decision_response_proto_goTypes = []interface{}{
	(ModificationsType)(0),         // 0: flagship.protobuf.ModificationsType
	(*CampaignIdVariationId)(nil),  // 1: flagship.protobuf.CampaignIdVariationId
	(*Modifications)(nil),          // 2: flagship.protobuf.Modifications
	(*TuringEngineOptions)(nil),    // 3: flagship.protobuf.TuringEngineOptions
	(*Variation)(nil),              // 4: flagship.protobuf.Variation
	(*FullVariation)(nil),          // 5: flagship.protobuf.FullVariation
	(*Campaign)(nil),               // 6: flagship.protobuf.Campaign
	(*AccountSettings)(nil),        // 7: flagship.protobuf.AccountSettings
	(*DecisionResponse)(nil),       // 8: flagship.protobuf.DecisionResponse
	(*DecisionResponsePanic)(nil),  // 9: flagship.protobuf.DecisionResponsePanic
	(*DecisionResponseFull)(nil),   // 10: flagship.protobuf.DecisionResponseFull
	(*DecisionResponseSimple)(nil), // 11: flagship.protobuf.DecisionResponseSimple
	nil,                            // 12: flagship.protobuf.TuringEngineOptions.ContextKeysEntry
	(*structpb.Struct)(nil),        // 13: google.protobuf.Struct
	(*wrapperspb.StringValue)(nil), // 14: google.protobuf.StringValue
}
var file_decision_response_decision_response_proto_depIdxs = []int32{
	0,  // 0: flagship.protobuf.Modifications.type:type_name -> flagship.protobuf.ModificationsType
	13, // 1: flagship.protobuf.Modifications.value:type_name -> google.protobuf.Struct
	12, // 2: flagship.protobuf.TuringEngineOptions.context_keys:type_name -> flagship.protobuf.TuringEngineOptions.ContextKeysEntry
	14, // 3: flagship.protobuf.Variation.id:type_name -> google.protobuf.StringValue
	2,  // 4: flagship.protobuf.Variation.modifications:type_name -> flagship.protobuf.Modifications
	14, // 5: flagship.protobuf.FullVariation.id:type_name -> google.protobuf.StringValue
	2,  // 6: flagship.protobuf.FullVariation.modifications:type_name -> flagship.protobuf.Modifications
	3,  // 7: flagship.protobuf.FullVariation.te_options:type_name -> flagship.protobuf.TuringEngineOptions
	14, // 8: flagship.protobuf.Campaign.id:type_name -> google.protobuf.StringValue
	14, // 9: flagship.protobuf.Campaign.variation_group_id:type_name -> google.protobuf.StringValue
	4,  // 10: flagship.protobuf.Campaign.variation:type_name -> flagship.protobuf.Variation
	14, // 11: flagship.protobuf.DecisionResponse.visitor_id:type_name -> google.protobuf.StringValue
	6,  // 12: flagship.protobuf.DecisionResponse.campaigns:type_name -> flagship.protobuf.Campaign
	7,  // 13: flagship.protobuf.DecisionResponse.accountSettings:type_name -> flagship.protobuf.AccountSettings
	14, // 14: flagship.protobuf.DecisionResponsePanic.visitor_id:type_name -> google.protobuf.StringValue
	6,  // 15: flagship.protobuf.DecisionResponsePanic.campaigns:type_name -> flagship.protobuf.Campaign
	14, // 16: flagship.protobuf.DecisionResponseFull.visitor_id:type_name -> google.protobuf.StringValue
	6,  // 17: flagship.protobuf.DecisionResponseFull.campaigns:type_name -> flagship.protobuf.Campaign
	1,  // 18: flagship.protobuf.DecisionResponseFull.campaigns_variation:type_name -> flagship.protobuf.CampaignIdVariationId
	13, // 19: flagship.protobuf.DecisionResponseFull.merged_modifications:type_name -> google.protobuf.Struct
	1,  // 20: flagship.protobuf.DecisionResponseSimple.campaigns_variation:type_name -> flagship.protobuf.CampaignIdVariationId
	13, // 21: flagship.protobuf.DecisionResponseSimple.merged_modifications:type_name -> google.protobuf.Struct
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_decision_response_decision_response_proto_init() }
func file_decision_response_decision_response_proto_init() {
	if File_decision_response_decision_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_decision_response_decision_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CampaignIdVariationId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Modifications); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TuringEngineOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Variation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullVariation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Campaign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecisionResponsePanic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecisionResponseFull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decision_response_decision_response_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecisionResponseSimple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_decision_response_decision_response_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_decision_response_decision_response_proto_goTypes,
		DependencyIndexes: file_decision_response_decision_response_proto_depIdxs,
		EnumInfos:         file_decision_response_decision_response_proto_enumTypes,
		MessageInfos:      file_decision_response_decision_response_proto_msgTypes,
	}.Build()
	File_decision_response_decision_response_proto = out.File
	file_decision_response_decision_response_proto_rawDesc = nil
	file_decision_response_decision_response_proto_goTypes = nil
	file_decision_response_decision_response_proto_depIdxs = nil
}
