// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: activate_request/activate_request.proto

package activate_request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// client ID
	//
	// # Required
	//
	// The generated client ID.
	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// *
	// anonymous ID
	//
	// # Optional
	//
	// The initial anonymous ID for the visitor.
	Aid *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=aid,proto3" json:"aid,omitempty"`
	// *
	// visitor ID
	//
	// # Required
	//
	// The custom or decision generated visitor ID.
	Vid string `protobuf:"bytes,3,opt,name=vid,proto3" json:"vid,omitempty"`
	// *
	// variation ID
	//
	// # Required
	//
	// The generated variation ID.
	Vaid string `protobuf:"bytes,4,opt,name=vaid,proto3" json:"vaid,omitempty"`
	// *
	// campaign ID
	//
	// # Required
	//
	// The generated campaign ID.
	Caid string `protobuf:"bytes,5,opt,name=caid,proto3" json:"caid,omitempty"`
	// *
	// custom visitor ID
	//
	// # Required
	//
	// The custom visitor ID set by the client
	Cvid string `protobuf:"bytes,6,opt,name=cvid,proto3" json:"cvid,omitempty"`
	// *
	// queue time
	//
	// # Required
	//
	// The queue time to express the delay between the activation and when it was sent
	Qt int64 `protobuf:"varint,7,opt,name=qt,proto3" json:"qt,omitempty"`
	// *
	// qa
	//
	// # Optional
	//
	// The QA parameter to enable the QA mode for the data collect hit
	Qa bool `protobuf:"varint,8,opt,name=qa,proto3" json:"qa,omitempty"`
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activate_request_activate_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activate_request_activate_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_activate_request_activate_request_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ActivateRequest) GetAid() *wrapperspb.StringValue {
	if x != nil {
		return x.Aid
	}
	return nil
}

func (x *ActivateRequest) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *ActivateRequest) GetVaid() string {
	if x != nil {
		return x.Vaid
	}
	return ""
}

func (x *ActivateRequest) GetCaid() string {
	if x != nil {
		return x.Caid
	}
	return ""
}

func (x *ActivateRequest) GetCvid() string {
	if x != nil {
		return x.Cvid
	}
	return ""
}

func (x *ActivateRequest) GetQt() int64 {
	if x != nil {
		return x.Qt
	}
	return 0
}

func (x *ActivateRequest) GetQa() bool {
	if x != nil {
		return x.Qa
	}
	return false
}

type ActivateRequestBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// client ID
	//
	// # Required
	//
	// The generated client ID.
	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// *
	// batch data
	//
	// # Required
	//
	// The list of ActivateRequest.
	Batch []*ActivateRequest `protobuf:"bytes,2,rep,name=batch,proto3" json:"batch,omitempty"`
}

func (x *ActivateRequestBatch) Reset() {
	*x = ActivateRequestBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activate_request_activate_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateRequestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequestBatch) ProtoMessage() {}

func (x *ActivateRequestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_activate_request_activate_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequestBatch.ProtoReflect.Descriptor instead.
func (*ActivateRequestBatch) Descriptor() ([]byte, []int) {
	return file_activate_request_activate_request_proto_rawDescGZIP(), []int{1}
}

func (x *ActivateRequestBatch) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ActivateRequestBatch) GetBatch() []*ActivateRequest {
	if x != nil {
		return x.Batch
	}
	return nil
}

var File_activate_request_activate_request_proto protoreflect.FileDescriptor

var file_activate_request_activate_request_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6c, 0x61, 0x67, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a,
	0x0f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63,
	0x69, 0x64, 0x12, 0x2e, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x61,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x76, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x76, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x76, 0x69, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x71, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x71, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x71, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x71, 0x61,
	0x22, 0x62, 0x0a, 0x14, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x05, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x6c, 0x61, 0x67,
	0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2d, 0x69, 0x6f, 0x2f, 0x66,
	0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_activate_request_activate_request_proto_rawDescOnce sync.Once
	file_activate_request_activate_request_proto_rawDescData = file_activate_request_activate_request_proto_rawDesc
)

func file_activate_request_activate_request_proto_rawDescGZIP() []byte {
	file_activate_request_activate_request_proto_rawDescOnce.Do(func() {
		file_activate_request_activate_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_activate_request_activate_request_proto_rawDescData)
	})
	return file_activate_request_activate_request_proto_rawDescData
}

var file_activate_request_activate_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_activate_request_activate_request_proto_goTypes = []interface{}{
	(*ActivateRequest)(nil),        // 0: flagship.protobuf.ActivateRequest
	(*ActivateRequestBatch)(nil),   // 1: flagship.protobuf.ActivateRequestBatch
	(*wrapperspb.StringValue)(nil), // 2: google.protobuf.StringValue
}
var file_activate_request_activate_request_proto_depIdxs = []int32{
	2, // 0: flagship.protobuf.ActivateRequest.aid:type_name -> google.protobuf.StringValue
	0, // 1: flagship.protobuf.ActivateRequestBatch.batch:type_name -> flagship.protobuf.ActivateRequest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_activate_request_activate_request_proto_init() }
func file_activate_request_activate_request_proto_init() {
	if File_activate_request_activate_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_activate_request_activate_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activate_request_activate_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateRequestBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activate_request_activate_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activate_request_activate_request_proto_goTypes,
		DependencyIndexes: file_activate_request_activate_request_proto_depIdxs,
		MessageInfos:      file_activate_request_activate_request_proto_msgTypes,
	}.Build()
	File_activate_request_activate_request_proto = out.File
	file_activate_request_activate_request_proto_rawDesc = nil
	file_activate_request_activate_request_proto_goTypes = nil
	file_activate_request_activate_request_proto_depIdxs = nil
}
