// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: activate_request/activate_request.proto

package activate_request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// client ID
	//
	// Required
	//
	// The generated client ID.
	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	//*
	// anonymous ID
	//
	// Optional
	//
	// The initial anonymous ID for the visitor.
	Aid *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=aid,proto3" json:"aid,omitempty"`
	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	Vid string `protobuf:"bytes,3,opt,name=vid,proto3" json:"vid,omitempty"`
	//*
	// variation ID
	//
	// Required
	//
	// The generated variation ID.
	Vaid string `protobuf:"bytes,4,opt,name=vaid,proto3" json:"vaid,omitempty"`
	//*
	// campaign ID
	//
	// Required
	//
	// The generated campaign ID.
	Caid string `protobuf:"bytes,5,opt,name=caid,proto3" json:"caid,omitempty"`
	//*
	// custom visitor ID
	//
	// Required
	//
	// The custom visitor ID set by the client
	Cvid string `protobuf:"bytes,6,opt,name=cvid,proto3" json:"cvid,omitempty"`
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activate_request_activate_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activate_request_activate_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_activate_request_activate_request_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ActivateRequest) GetAid() *wrapperspb.StringValue {
	if x != nil {
		return x.Aid
	}
	return nil
}

func (x *ActivateRequest) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *ActivateRequest) GetVaid() string {
	if x != nil {
		return x.Vaid
	}
	return ""
}

func (x *ActivateRequest) GetCaid() string {
	if x != nil {
		return x.Caid
	}
	return ""
}

func (x *ActivateRequest) GetCvid() string {
	if x != nil {
		return x.Cvid
	}
	return ""
}

type ActivateRequestMultipleInner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	VisitorId string `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	//*
	// anonymous ID
	//
	// Optional
	//
	// The initial anonymous ID for the visitor.
	AnonymousId *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	//*
	// variation ID
	//
	// The generated variation ID.
	VariationId string `protobuf:"bytes,3,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	//*
	// variation group ID
	//
	// Required
	//
	// The generated variation group ID.
	VariationGroupId string `protobuf:"bytes,4,opt,name=variation_group_id,json=variationGroupId,proto3" json:"variation_group_id,omitempty"`
}

func (x *ActivateRequestMultipleInner) Reset() {
	*x = ActivateRequestMultipleInner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activate_request_activate_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateRequestMultipleInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequestMultipleInner) ProtoMessage() {}

func (x *ActivateRequestMultipleInner) ProtoReflect() protoreflect.Message {
	mi := &file_activate_request_activate_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequestMultipleInner.ProtoReflect.Descriptor instead.
func (*ActivateRequestMultipleInner) Descriptor() ([]byte, []int) {
	return file_activate_request_activate_request_proto_rawDescGZIP(), []int{1}
}

func (x *ActivateRequestMultipleInner) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *ActivateRequestMultipleInner) GetAnonymousId() *wrapperspb.StringValue {
	if x != nil {
		return x.AnonymousId
	}
	return nil
}

func (x *ActivateRequestMultipleInner) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

func (x *ActivateRequestMultipleInner) GetVariationGroupId() string {
	if x != nil {
		return x.VariationGroupId
	}
	return ""
}

type ActivateRequestMultiple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// environment ID
	//
	// Required
	//
	// The generated environment ID.
	EnvironmentId string `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	//*
	// visitor ID
	//
	// The custom or decision generated visitor ID.
	VisitorId string `protobuf:"bytes,2,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	//*
	// anonymous ID
	//
	// Optional
	//
	// The initial anonymous ID for the visitor.
	AnonymousId *wrapperspb.StringValue         `protobuf:"bytes,3,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	Activations []*ActivateRequestMultipleInner `protobuf:"bytes,4,rep,name=activations,proto3" json:"activations,omitempty"`
}

func (x *ActivateRequestMultiple) Reset() {
	*x = ActivateRequestMultiple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activate_request_activate_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateRequestMultiple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequestMultiple) ProtoMessage() {}

func (x *ActivateRequestMultiple) ProtoReflect() protoreflect.Message {
	mi := &file_activate_request_activate_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequestMultiple.ProtoReflect.Descriptor instead.
func (*ActivateRequestMultiple) Descriptor() ([]byte, []int) {
	return file_activate_request_activate_request_proto_rawDescGZIP(), []int{2}
}

func (x *ActivateRequestMultiple) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ActivateRequestMultiple) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *ActivateRequestMultiple) GetAnonymousId() *wrapperspb.StringValue {
	if x != nil {
		return x.AnonymousId
	}
	return nil
}

func (x *ActivateRequestMultiple) GetActivations() []*ActivateRequestMultipleInner {
	if x != nil {
		return x.Activations
	}
	return nil
}

var File_activate_request_activate_request_proto protoreflect.FileDescriptor

var file_activate_request_activate_request_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6c, 0x61, 0x67, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a,
	0x0f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63,
	0x69, 0x64, 0x12, 0x2e, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x61,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x76, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x76, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x76, 0x69, 0x64,
	0x22, 0xcf, 0x01, 0x0a, 0x1c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x3f, 0x0a, 0x0c, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x22, 0xf3, 0x01, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0c, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d,
	0x6f, 0x75, 0x73, 0x49, 0x64, 0x12, 0x51, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x0b, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2d,
	0x69, 0x6f, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_activate_request_activate_request_proto_rawDescOnce sync.Once
	file_activate_request_activate_request_proto_rawDescData = file_activate_request_activate_request_proto_rawDesc
)

func file_activate_request_activate_request_proto_rawDescGZIP() []byte {
	file_activate_request_activate_request_proto_rawDescOnce.Do(func() {
		file_activate_request_activate_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_activate_request_activate_request_proto_rawDescData)
	})
	return file_activate_request_activate_request_proto_rawDescData
}

var file_activate_request_activate_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_activate_request_activate_request_proto_goTypes = []interface{}{
	(*ActivateRequest)(nil),              // 0: flagship.protobuf.ActivateRequest
	(*ActivateRequestMultipleInner)(nil), // 1: flagship.protobuf.ActivateRequestMultipleInner
	(*ActivateRequestMultiple)(nil),      // 2: flagship.protobuf.ActivateRequestMultiple
	(*wrapperspb.StringValue)(nil),       // 3: google.protobuf.StringValue
}
var file_activate_request_activate_request_proto_depIdxs = []int32{
	3, // 0: flagship.protobuf.ActivateRequest.aid:type_name -> google.protobuf.StringValue
	3, // 1: flagship.protobuf.ActivateRequestMultipleInner.anonymous_id:type_name -> google.protobuf.StringValue
	3, // 2: flagship.protobuf.ActivateRequestMultiple.anonymous_id:type_name -> google.protobuf.StringValue
	1, // 3: flagship.protobuf.ActivateRequestMultiple.activations:type_name -> flagship.protobuf.ActivateRequestMultipleInner
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_activate_request_activate_request_proto_init() }
func file_activate_request_activate_request_proto_init() {
	if File_activate_request_activate_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_activate_request_activate_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activate_request_activate_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateRequestMultipleInner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activate_request_activate_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateRequestMultiple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activate_request_activate_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activate_request_activate_request_proto_goTypes,
		DependencyIndexes: file_activate_request_activate_request_proto_depIdxs,
		MessageInfos:      file_activate_request_activate_request_proto_msgTypes,
	}.Build()
	File_activate_request_activate_request_proto = out.File
	file_activate_request_activate_request_proto_rawDesc = nil
	file_activate_request_activate_request_proto_goTypes = nil
	file_activate_request_activate_request_proto_depIdxs = nil
}
