// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: flags/flags.proto

package flags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlagInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// flags map
	//
	// # Required
	//
	// The map of flag name / flag information
	Flags map[string]*FlagInfo `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FlagInfos) Reset() {
	*x = FlagInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flags_flags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagInfos) ProtoMessage() {}

func (x *FlagInfos) ProtoReflect() protoreflect.Message {
	mi := &file_flags_flags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagInfos.ProtoReflect.Descriptor instead.
func (*FlagInfos) Descriptor() ([]byte, []int) {
	return file_flags_flags_proto_rawDescGZIP(), []int{0}
}

func (x *FlagInfos) GetFlags() map[string]*FlagInfo {
	if x != nil {
		return x.Flags
	}
	return nil
}

type FlagInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// value
	//
	// # Required
	//
	// The flag value
	Value *structpb.Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// *
	// metadata
	//
	// # Required
	//
	// The flag metadata
	Metadata *FlagMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *FlagInfo) Reset() {
	*x = FlagInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flags_flags_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagInfo) ProtoMessage() {}

func (x *FlagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flags_flags_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagInfo.ProtoReflect.Descriptor instead.
func (*FlagInfo) Descriptor() ([]byte, []int) {
	return file_flags_flags_proto_rawDescGZIP(), []int{1}
}

func (x *FlagInfo) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FlagInfo) GetMetadata() *FlagMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FlagMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// campaign id
	//
	// # Required
	//
	// The campaign id
	CampaignId string `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	// *
	// variation group id
	//
	// # Required
	//
	// The variation group id
	Variation_GroupId string `protobuf:"bytes,2,opt,name=variation__group_id,json=variationGroupId,proto3" json:"variation__group_id,omitempty"`
	// *
	// variation id
	//
	// # Required
	//
	// The variation id
	VariationId string `protobuf:"bytes,3,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
}

func (x *FlagMetadata) Reset() {
	*x = FlagMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flags_flags_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagMetadata) ProtoMessage() {}

func (x *FlagMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_flags_flags_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagMetadata.ProtoReflect.Descriptor instead.
func (*FlagMetadata) Descriptor() ([]byte, []int) {
	return file_flags_flags_proto_rawDescGZIP(), []int{2}
}

func (x *FlagMetadata) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *FlagMetadata) GetVariation_GroupId() string {
	if x != nil {
		return x.Variation_GroupId
	}
	return ""
}

func (x *FlagMetadata) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

var File_flags_flags_proto protoreflect.FileDescriptor

var file_flags_flags_proto_rawDesc = []byte{
	0x0a, 0x11, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x09, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x12, 0x3d, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x2e,
	0x46, 0x6c, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67,
	0x73, 0x1a, 0x55, 0x0a, 0x0a, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x75, 0x0a, 0x08, 0x46, 0x6c, 0x61, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x81, 0x01, 0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49,
	0x64, 0x12, 0x2d, 0x0a, 0x13, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2d, 0x69, 0x6f, 0x2f, 0x66, 0x6c,
	0x61, 0x67, 0x73, 0x68, 0x69, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flags_flags_proto_rawDescOnce sync.Once
	file_flags_flags_proto_rawDescData = file_flags_flags_proto_rawDesc
)

func file_flags_flags_proto_rawDescGZIP() []byte {
	file_flags_flags_proto_rawDescOnce.Do(func() {
		file_flags_flags_proto_rawDescData = protoimpl.X.CompressGZIP(file_flags_flags_proto_rawDescData)
	})
	return file_flags_flags_proto_rawDescData
}

var file_flags_flags_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_flags_flags_proto_goTypes = []interface{}{
	(*FlagInfos)(nil),      // 0: flagship.protobuf.FlagInfos
	(*FlagInfo)(nil),       // 1: flagship.protobuf.FlagInfo
	(*FlagMetadata)(nil),   // 2: flagship.protobuf.FlagMetadata
	nil,                    // 3: flagship.protobuf.FlagInfos.FlagsEntry
	(*structpb.Value)(nil), // 4: google.protobuf.Value
}
var file_flags_flags_proto_depIdxs = []int32{
	3, // 0: flagship.protobuf.FlagInfos.flags:type_name -> flagship.protobuf.FlagInfos.FlagsEntry
	4, // 1: flagship.protobuf.FlagInfo.value:type_name -> google.protobuf.Value
	2, // 2: flagship.protobuf.FlagInfo.metadata:type_name -> flagship.protobuf.FlagMetadata
	1, // 3: flagship.protobuf.FlagInfos.FlagsEntry.value:type_name -> flagship.protobuf.FlagInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_flags_flags_proto_init() }
func file_flags_flags_proto_init() {
	if File_flags_flags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flags_flags_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flags_flags_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flags_flags_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flags_flags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flags_flags_proto_goTypes,
		DependencyIndexes: file_flags_flags_proto_depIdxs,
		MessageInfos:      file_flags_flags_proto_msgTypes,
	}.Build()
	File_flags_flags_proto = out.File
	file_flags_flags_proto_rawDesc = nil
	file_flags_flags_proto_goTypes = nil
	file_flags_flags_proto_depIdxs = nil
}
