// Code generated by protoc-gen-go. DO NOT EDIT.
// source: targeting/targeting.proto

package targeting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Targeting_TargetingOperator int32

const (
	Targeting_NULL                   Targeting_TargetingOperator = 0
	Targeting_LOWER_THAN             Targeting_TargetingOperator = 1
	Targeting_GREATER_THAN_OR_EQUALS Targeting_TargetingOperator = 2
	Targeting_LOWER_THAN_OR_EQUALS   Targeting_TargetingOperator = 3
	Targeting_EQUALS                 Targeting_TargetingOperator = 4
	Targeting_NOT_EQUALS             Targeting_TargetingOperator = 5
	Targeting_STARTS_WITH            Targeting_TargetingOperator = 6
	Targeting_ENDS_WITH              Targeting_TargetingOperator = 7
	Targeting_CONTAINS               Targeting_TargetingOperator = 8
	Targeting_NOT_CONTAINS           Targeting_TargetingOperator = 9
	Targeting_GREATER_THAN           Targeting_TargetingOperator = 10
)

var Targeting_TargetingOperator_name = map[int32]string{
	0:  "NULL",
	1:  "LOWER_THAN",
	2:  "GREATER_THAN_OR_EQUALS",
	3:  "LOWER_THAN_OR_EQUALS",
	4:  "EQUALS",
	5:  "NOT_EQUALS",
	6:  "STARTS_WITH",
	7:  "ENDS_WITH",
	8:  "CONTAINS",
	9:  "NOT_CONTAINS",
	10: "GREATER_THAN",
}

var Targeting_TargetingOperator_value = map[string]int32{
	"NULL":                   0,
	"LOWER_THAN":             1,
	"GREATER_THAN_OR_EQUALS": 2,
	"LOWER_THAN_OR_EQUALS":   3,
	"EQUALS":                 4,
	"NOT_EQUALS":             5,
	"STARTS_WITH":            6,
	"ENDS_WITH":              7,
	"CONTAINS":               8,
	"NOT_CONTAINS":           9,
	"GREATER_THAN":           10,
}

func (x Targeting_TargetingOperator) String() string {
	return proto.EnumName(Targeting_TargetingOperator_name, int32(x))
}

func (Targeting_TargetingOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89898cd1f7050311, []int{0, 0}
}

type Targeting struct {
	TargetingGroups      []*Targeting_TargetingGroup `protobuf:"bytes,1,rep,name=targeting_groups,json=targetingGroups,proto3" json:"targeting_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Targeting) Reset()         { *m = Targeting{} }
func (m *Targeting) String() string { return proto.CompactTextString(m) }
func (*Targeting) ProtoMessage()    {}
func (*Targeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_89898cd1f7050311, []int{0}
}

func (m *Targeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Targeting.Unmarshal(m, b)
}
func (m *Targeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Targeting.Marshal(b, m, deterministic)
}
func (m *Targeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Targeting.Merge(m, src)
}
func (m *Targeting) XXX_Size() int {
	return xxx_messageInfo_Targeting.Size(m)
}
func (m *Targeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Targeting.DiscardUnknown(m)
}

var xxx_messageInfo_Targeting proto.InternalMessageInfo

func (m *Targeting) GetTargetingGroups() []*Targeting_TargetingGroup {
	if m != nil {
		return m.TargetingGroups
	}
	return nil
}

type Targeting_InnerTargeting struct {
	//*
	// targeting operator
	//
	// Required
	//
	// The operator for the targeting
	Operator Targeting_TargetingOperator `protobuf:"varint,1,opt,name=operator,proto3,enum=flagship.protobuf.Targeting_TargetingOperator" json:"operator,omitempty"`
	//*
	// key
	//
	// Required
	//
	// The targeting key for the context
	Key *wrappers.StringValue `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	//*
	// value
	//
	// Required
	//
	// The targeting value
	Value                *_struct.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Targeting_InnerTargeting) Reset()         { *m = Targeting_InnerTargeting{} }
func (m *Targeting_InnerTargeting) String() string { return proto.CompactTextString(m) }
func (*Targeting_InnerTargeting) ProtoMessage()    {}
func (*Targeting_InnerTargeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_89898cd1f7050311, []int{0, 0}
}

func (m *Targeting_InnerTargeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Targeting_InnerTargeting.Unmarshal(m, b)
}
func (m *Targeting_InnerTargeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Targeting_InnerTargeting.Marshal(b, m, deterministic)
}
func (m *Targeting_InnerTargeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Targeting_InnerTargeting.Merge(m, src)
}
func (m *Targeting_InnerTargeting) XXX_Size() int {
	return xxx_messageInfo_Targeting_InnerTargeting.Size(m)
}
func (m *Targeting_InnerTargeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Targeting_InnerTargeting.DiscardUnknown(m)
}

var xxx_messageInfo_Targeting_InnerTargeting proto.InternalMessageInfo

func (m *Targeting_InnerTargeting) GetOperator() Targeting_TargetingOperator {
	if m != nil {
		return m.Operator
	}
	return Targeting_NULL
}

func (m *Targeting_InnerTargeting) GetKey() *wrappers.StringValue {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Targeting_InnerTargeting) GetValue() *_struct.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Targeting_TargetingGroup struct {
	//*
	// visitor ID
	//
	// Required
	//
	// The custom or decision generated visitor ID.
	Targetings           []*Targeting_InnerTargeting `protobuf:"bytes,1,rep,name=targetings,proto3" json:"targetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Targeting_TargetingGroup) Reset()         { *m = Targeting_TargetingGroup{} }
func (m *Targeting_TargetingGroup) String() string { return proto.CompactTextString(m) }
func (*Targeting_TargetingGroup) ProtoMessage()    {}
func (*Targeting_TargetingGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_89898cd1f7050311, []int{0, 1}
}

func (m *Targeting_TargetingGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Targeting_TargetingGroup.Unmarshal(m, b)
}
func (m *Targeting_TargetingGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Targeting_TargetingGroup.Marshal(b, m, deterministic)
}
func (m *Targeting_TargetingGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Targeting_TargetingGroup.Merge(m, src)
}
func (m *Targeting_TargetingGroup) XXX_Size() int {
	return xxx_messageInfo_Targeting_TargetingGroup.Size(m)
}
func (m *Targeting_TargetingGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_Targeting_TargetingGroup.DiscardUnknown(m)
}

var xxx_messageInfo_Targeting_TargetingGroup proto.InternalMessageInfo

func (m *Targeting_TargetingGroup) GetTargetings() []*Targeting_InnerTargeting {
	if m != nil {
		return m.Targetings
	}
	return nil
}

func init() {
	proto.RegisterEnum("flagship.protobuf.Targeting_TargetingOperator", Targeting_TargetingOperator_name, Targeting_TargetingOperator_value)
	proto.RegisterType((*Targeting)(nil), "flagship.protobuf.Targeting")
	proto.RegisterType((*Targeting_InnerTargeting)(nil), "flagship.protobuf.Targeting.InnerTargeting")
	proto.RegisterType((*Targeting_TargetingGroup)(nil), "flagship.protobuf.Targeting.TargetingGroup")
}

func init() { proto.RegisterFile("targeting/targeting.proto", fileDescriptor_89898cd1f7050311) }

var fileDescriptor_89898cd1f7050311 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x8e, 0x93, 0x40,
	0x14, 0x96, 0xa5, 0x5b, 0xe9, 0xe9, 0xca, 0xce, 0x4e, 0xcc, 0x06, 0xc9, 0xc6, 0x34, 0x7b, 0xd5,
	0x44, 0x85, 0x58, 0x9f, 0x00, 0x95, 0xec, 0x56, 0x09, 0xc4, 0x61, 0x76, 0x37, 0x31, 0x31, 0x84,
	0x36, 0x74, 0x4a, 0xac, 0x0c, 0x19, 0x06, 0x8d, 0xaf, 0xe6, 0x5b, 0x18, 0x5f, 0xc8, 0x50, 0xfe,
	0xda, 0xed, 0x4d, 0xef, 0xce, 0xf9, 0x7e, 0xe6, 0xe3, 0x3b, 0x01, 0x5e, 0xc8, 0x58, 0xb0, 0x44,
	0xa6, 0x19, 0xb3, 0xbb, 0xc9, 0xca, 0x05, 0x97, 0x1c, 0x5f, 0xac, 0x36, 0x31, 0x2b, 0xd6, 0x69,
	0x5e, 0xef, 0x8b, 0x72, 0x65, 0xbe, 0x64, 0x9c, 0xb3, 0x4d, 0x62, 0xb7, 0x80, 0xfd, 0x4b, 0xc4,
	0x79, 0x9e, 0x88, 0xa2, 0x96, 0x98, 0x57, 0x8f, 0xf9, 0x42, 0x8a, 0x72, 0x29, 0x6b, 0xf6, 0xfa,
	0xdf, 0x00, 0x46, 0xb4, 0x0d, 0xc1, 0xf7, 0x80, 0xba, 0xc4, 0x88, 0x09, 0x5e, 0xe6, 0x85, 0xa1,
	0x4c, 0xd4, 0xe9, 0x78, 0xf6, 0xca, 0x3a, 0x48, 0xb6, 0x3a, 0x5f, 0x3f, 0xdd, 0x54, 0x1e, 0x72,
	0x2e, 0xf7, 0xf6, 0xc2, 0xfc, 0xa3, 0x80, 0x3e, 0xcf, 0xb2, 0x44, 0xf4, 0x51, 0x9f, 0x40, 0xe3,
	0x79, 0x22, 0x62, 0xc9, 0x85, 0xa1, 0x4c, 0x94, 0xa9, 0x3e, 0xb3, 0x8e, 0x8b, 0x08, 0x1a, 0x17,
	0xe9, 0xfc, 0xd8, 0x02, 0xf5, 0x7b, 0xf2, 0xdb, 0x38, 0x99, 0x28, 0xd3, 0xf1, 0xec, 0xca, 0xaa,
	0x0b, 0xf7, 0x8f, 0x84, 0x52, 0xa4, 0x19, 0xbb, 0x8f, 0x37, 0x65, 0x42, 0x2a, 0x21, 0x7e, 0x0d,
	0xa7, 0x3f, 0xab, 0xcd, 0x50, 0xb7, 0x8e, 0xcb, 0x03, 0x47, 0xad, 0xad, 0x45, 0xe6, 0x37, 0xd0,
	0xf7, 0xfb, 0xe1, 0xcf, 0x00, 0x5d, 0xc3, 0xe3, 0x0e, 0xb4, 0x5f, 0x9e, 0xec, 0xd8, 0xaf, 0xff,
	0x2a, 0x70, 0x71, 0x50, 0x0e, 0x6b, 0x30, 0xf0, 0xef, 0x3c, 0x0f, 0x3d, 0xc1, 0x3a, 0x80, 0x17,
	0x3c, 0xb8, 0x24, 0xa2, 0xb7, 0x8e, 0x8f, 0x14, 0x6c, 0xc2, 0xe5, 0x0d, 0x71, 0x1d, 0xda, 0x20,
	0x51, 0x40, 0x22, 0xf7, 0xcb, 0x9d, 0xe3, 0x85, 0xe8, 0x04, 0x1b, 0xf0, 0xbc, 0xd7, 0xee, 0x30,
	0x2a, 0x06, 0x18, 0x36, 0xf3, 0xa0, 0x7a, 0xd1, 0x0f, 0x68, 0xcb, 0x9d, 0xe2, 0x73, 0x18, 0x87,
	0xd4, 0x21, 0x34, 0x8c, 0x1e, 0xe6, 0xf4, 0x16, 0x0d, 0xf1, 0x33, 0x18, 0xb9, 0xfe, 0xc7, 0x66,
	0x7d, 0x8a, 0xcf, 0x40, 0xfb, 0x10, 0xf8, 0xd4, 0x99, 0xfb, 0x21, 0xd2, 0x30, 0x82, 0xb3, 0xca,
	0xdd, 0x21, 0xa3, 0x0a, 0xd9, 0xfd, 0x22, 0x04, 0xef, 0xdf, 0x7e, 0xb5, 0x59, 0x2a, 0xd7, 0xe5,
	0xc2, 0x5a, 0xf2, 0x1f, 0x76, 0x7b, 0x98, 0x37, 0x29, 0xef, 0xe7, 0xed, 0x91, 0xfa, 0xff, 0x7b,
	0x31, 0xdc, 0x02, 0xef, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x44, 0x0b, 0x52, 0x1c, 0xfd, 0x02,
	0x00, 0x00,
}
