// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bucketing/bucketing.proto

package bucketing

import (
	fmt "fmt"
	decision_response "github.com/flagship-io/flagship-proto/decision_response"
	targeting "github.com/flagship-io/flagship-proto/targeting"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bucketing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucketing) Reset()         { *m = Bucketing{} }
func (m *Bucketing) String() string { return proto.CompactTextString(m) }
func (*Bucketing) ProtoMessage()    {}
func (*Bucketing) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc1e7610a31616c, []int{0}
}

func (m *Bucketing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucketing.Unmarshal(m, b)
}
func (m *Bucketing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucketing.Marshal(b, m, deterministic)
}
func (m *Bucketing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucketing.Merge(m, src)
}
func (m *Bucketing) XXX_Size() int {
	return xxx_messageInfo_Bucketing.Size(m)
}
func (m *Bucketing) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucketing.DiscardUnknown(m)
}

var xxx_messageInfo_Bucketing proto.InternalMessageInfo

type Bucketing_BucketingResponse struct {
	GeneratedAt          string                         `protobuf:"bytes,1,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	VisitorConsolidation bool                           `protobuf:"varint,2,opt,name=visitor_consolidation,json=visitorConsolidation,proto3" json:"visitor_consolidation,omitempty"`
	Panic                bool                           `protobuf:"varint,3,opt,name=panic,proto3" json:"panic,omitempty"`
	Campaigns            []*Bucketing_BucketingCampaign `protobuf:"bytes,4,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Bucketing_BucketingResponse) Reset()         { *m = Bucketing_BucketingResponse{} }
func (m *Bucketing_BucketingResponse) String() string { return proto.CompactTextString(m) }
func (*Bucketing_BucketingResponse) ProtoMessage()    {}
func (*Bucketing_BucketingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc1e7610a31616c, []int{0, 0}
}

func (m *Bucketing_BucketingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucketing_BucketingResponse.Unmarshal(m, b)
}
func (m *Bucketing_BucketingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucketing_BucketingResponse.Marshal(b, m, deterministic)
}
func (m *Bucketing_BucketingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucketing_BucketingResponse.Merge(m, src)
}
func (m *Bucketing_BucketingResponse) XXX_Size() int {
	return xxx_messageInfo_Bucketing_BucketingResponse.Size(m)
}
func (m *Bucketing_BucketingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucketing_BucketingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Bucketing_BucketingResponse proto.InternalMessageInfo

func (m *Bucketing_BucketingResponse) GetGeneratedAt() string {
	if m != nil {
		return m.GeneratedAt
	}
	return ""
}

func (m *Bucketing_BucketingResponse) GetVisitorConsolidation() bool {
	if m != nil {
		return m.VisitorConsolidation
	}
	return false
}

func (m *Bucketing_BucketingResponse) GetPanic() bool {
	if m != nil {
		return m.Panic
	}
	return false
}

func (m *Bucketing_BucketingResponse) GetCampaigns() []*Bucketing_BucketingCampaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

type Bucketing_BucketingCampaign struct {
	Id                   string                                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomId             string                                `protobuf:"bytes,2,opt,name=custom_id,json=customId,proto3" json:"custom_id,omitempty"`
	Type                 string                                `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	VariationGroups      []*Bucketing_BucketingVariationGroups `protobuf:"bytes,4,rep,name=variation_groups,json=variationGroups,proto3" json:"variation_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Bucketing_BucketingCampaign) Reset()         { *m = Bucketing_BucketingCampaign{} }
func (m *Bucketing_BucketingCampaign) String() string { return proto.CompactTextString(m) }
func (*Bucketing_BucketingCampaign) ProtoMessage()    {}
func (*Bucketing_BucketingCampaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc1e7610a31616c, []int{0, 1}
}

func (m *Bucketing_BucketingCampaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucketing_BucketingCampaign.Unmarshal(m, b)
}
func (m *Bucketing_BucketingCampaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucketing_BucketingCampaign.Marshal(b, m, deterministic)
}
func (m *Bucketing_BucketingCampaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucketing_BucketingCampaign.Merge(m, src)
}
func (m *Bucketing_BucketingCampaign) XXX_Size() int {
	return xxx_messageInfo_Bucketing_BucketingCampaign.Size(m)
}
func (m *Bucketing_BucketingCampaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucketing_BucketingCampaign.DiscardUnknown(m)
}

var xxx_messageInfo_Bucketing_BucketingCampaign proto.InternalMessageInfo

func (m *Bucketing_BucketingCampaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bucketing_BucketingCampaign) GetCustomId() string {
	if m != nil {
		return m.CustomId
	}
	return ""
}

func (m *Bucketing_BucketingCampaign) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Bucketing_BucketingCampaign) GetVariationGroups() []*Bucketing_BucketingVariationGroups {
	if m != nil {
		return m.VariationGroups
	}
	return nil
}

type Bucketing_BucketingVariationGroups struct {
	Id                   string                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Targeting            *targeting.Targeting               `protobuf:"bytes,2,opt,name=targeting,proto3" json:"targeting,omitempty"`
	Variations           []*decision_response.FullVariation `protobuf:"bytes,3,rep,name=variations,proto3" json:"variations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *Bucketing_BucketingVariationGroups) Reset()         { *m = Bucketing_BucketingVariationGroups{} }
func (m *Bucketing_BucketingVariationGroups) String() string { return proto.CompactTextString(m) }
func (*Bucketing_BucketingVariationGroups) ProtoMessage()    {}
func (*Bucketing_BucketingVariationGroups) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc1e7610a31616c, []int{0, 2}
}

func (m *Bucketing_BucketingVariationGroups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucketing_BucketingVariationGroups.Unmarshal(m, b)
}
func (m *Bucketing_BucketingVariationGroups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucketing_BucketingVariationGroups.Marshal(b, m, deterministic)
}
func (m *Bucketing_BucketingVariationGroups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucketing_BucketingVariationGroups.Merge(m, src)
}
func (m *Bucketing_BucketingVariationGroups) XXX_Size() int {
	return xxx_messageInfo_Bucketing_BucketingVariationGroups.Size(m)
}
func (m *Bucketing_BucketingVariationGroups) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucketing_BucketingVariationGroups.DiscardUnknown(m)
}

var xxx_messageInfo_Bucketing_BucketingVariationGroups proto.InternalMessageInfo

func (m *Bucketing_BucketingVariationGroups) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bucketing_BucketingVariationGroups) GetTargeting() *targeting.Targeting {
	if m != nil {
		return m.Targeting
	}
	return nil
}

func (m *Bucketing_BucketingVariationGroups) GetVariations() []*decision_response.FullVariation {
	if m != nil {
		return m.Variations
	}
	return nil
}

type Bucketing_BucketingUpdateRequest struct {
	EnvironmentId        string   `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	RequestedAt          string   `protobuf:"bytes,2,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucketing_BucketingUpdateRequest) Reset()         { *m = Bucketing_BucketingUpdateRequest{} }
func (m *Bucketing_BucketingUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*Bucketing_BucketingUpdateRequest) ProtoMessage()    {}
func (*Bucketing_BucketingUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cc1e7610a31616c, []int{0, 3}
}

func (m *Bucketing_BucketingUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucketing_BucketingUpdateRequest.Unmarshal(m, b)
}
func (m *Bucketing_BucketingUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucketing_BucketingUpdateRequest.Marshal(b, m, deterministic)
}
func (m *Bucketing_BucketingUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucketing_BucketingUpdateRequest.Merge(m, src)
}
func (m *Bucketing_BucketingUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_Bucketing_BucketingUpdateRequest.Size(m)
}
func (m *Bucketing_BucketingUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucketing_BucketingUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Bucketing_BucketingUpdateRequest proto.InternalMessageInfo

func (m *Bucketing_BucketingUpdateRequest) GetEnvironmentId() string {
	if m != nil {
		return m.EnvironmentId
	}
	return ""
}

func (m *Bucketing_BucketingUpdateRequest) GetRequestedAt() string {
	if m != nil {
		return m.RequestedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Bucketing)(nil), "flagship.protobuf.Bucketing")
	proto.RegisterType((*Bucketing_BucketingResponse)(nil), "flagship.protobuf.Bucketing.BucketingResponse")
	proto.RegisterType((*Bucketing_BucketingCampaign)(nil), "flagship.protobuf.Bucketing.BucketingCampaign")
	proto.RegisterType((*Bucketing_BucketingVariationGroups)(nil), "flagship.protobuf.Bucketing.BucketingVariationGroups")
	proto.RegisterType((*Bucketing_BucketingUpdateRequest)(nil), "flagship.protobuf.Bucketing.BucketingUpdateRequest")
}

func init() { proto.RegisterFile("bucketing/bucketing.proto", fileDescriptor_4cc1e7610a31616c) }

var fileDescriptor_4cc1e7610a31616c = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x95, 0xdd, 0x16, 0x35, 0xb3, 0x50, 0xa8, 0x55, 0x50, 0x1a, 0x38, 0x2c, 0x48, 0x48,
	0xcb, 0x81, 0xac, 0x68, 0xc5, 0x85, 0x13, 0x6d, 0x25, 0x50, 0x25, 0x4e, 0x16, 0x70, 0xe0, 0x12,
	0x9c, 0xd8, 0x4d, 0x47, 0xec, 0xda, 0xc6, 0x76, 0x56, 0xe2, 0x81, 0x90, 0x78, 0x02, 0x5e, 0x83,
	0x57, 0x42, 0xd8, 0x89, 0x13, 0xb4, 0x8b, 0xc4, 0x6d, 0xfc, 0xcf, 0xff, 0x4f, 0xbe, 0x91, 0x1d,
	0x38, 0xa9, 0xda, 0xfa, 0x8b, 0x70, 0x28, 0x9b, 0x65, 0xac, 0x0a, 0x6d, 0x94, 0x53, 0xe4, 0xe8,
	0x7a, 0xc5, 0x1a, 0x7b, 0x83, 0x3a, 0x9c, 0xab, 0xf6, 0x3a, 0x7f, 0xc6, 0x45, 0x8d, 0x16, 0x95,
	0x2c, 0x8d, 0xb0, 0x5a, 0x49, 0x2b, 0x96, 0x5b, 0x4a, 0x70, 0xe7, 0x27, 0x8e, 0x99, 0x26, 0x0c,
	0x8e, 0x55, 0x68, 0x3d, 0xf9, 0xbe, 0x0f, 0xe9, 0x45, 0xff, 0xb1, 0xfc, 0x57, 0x02, 0x47, 0xf1,
	0x44, 0xbb, 0x21, 0xe4, 0x31, 0xdc, 0x6e, 0x84, 0x14, 0x86, 0x39, 0xc1, 0x4b, 0xe6, 0xb2, 0x64,
	0x9e, 0x2c, 0x52, 0x3a, 0x8b, 0xda, 0xb9, 0x23, 0x67, 0x70, 0x7f, 0x83, 0x16, 0x9d, 0x32, 0x65,
	0xad, 0xa4, 0x55, 0x2b, 0xe4, 0xcc, 0xa1, 0x92, 0xd9, 0x64, 0x9e, 0x2c, 0x0e, 0xe8, 0x71, 0xd7,
	0xbc, 0x1c, 0xf7, 0xc8, 0x31, 0xec, 0x6b, 0x26, 0xb1, 0xce, 0xa6, 0xde, 0x14, 0x0e, 0xe4, 0x1d,
	0xa4, 0x35, 0x5b, 0x6b, 0x86, 0x8d, 0xb4, 0xd9, 0xde, 0x7c, 0xba, 0x98, 0x9d, 0x16, 0xc5, 0xd6,
	0xfa, 0x45, 0xc4, 0x1c, 0xaa, 0xcb, 0x2e, 0x46, 0x87, 0x01, 0xf9, 0xcf, 0xf1, 0x46, 0xbd, 0x81,
	0x1c, 0xc2, 0x04, 0x79, 0xb7, 0xc7, 0x04, 0x39, 0x79, 0x08, 0x69, 0xdd, 0x5a, 0xa7, 0xd6, 0x25,
	0x72, 0x8f, 0x9c, 0xd2, 0x83, 0x20, 0x5c, 0x71, 0x42, 0x60, 0xcf, 0x7d, 0xd3, 0xc2, 0x53, 0xa6,
	0xd4, 0xd7, 0xe4, 0x33, 0xdc, 0xdb, 0x30, 0x83, 0x7e, 0x8f, 0xb2, 0x31, 0xaa, 0xd5, 0x3d, 0xeb,
	0xcb, 0xff, 0x63, 0xfd, 0xd8, 0xa7, 0xdf, 0xfa, 0x30, 0xbd, 0xbb, 0xf9, 0x5b, 0xc8, 0x7f, 0x24,
	0x90, 0xfd, 0xcb, 0xbd, 0xc5, 0xff, 0x0a, 0xd2, 0x78, 0xb1, 0x9e, 0x7f, 0x76, 0xfa, 0x68, 0x07,
	0xc7, 0xfb, 0xde, 0x43, 0x07, 0x3b, 0x79, 0x0d, 0x10, 0xbf, 0x6d, 0xb3, 0xa9, 0x5f, 0x62, 0xbe,
	0x23, 0xfc, 0xa6, 0x5d, 0xad, 0x22, 0x07, 0x1d, 0x65, 0xf2, 0x0a, 0x1e, 0x44, 0xd2, 0x0f, 0x9a,
	0x33, 0x27, 0xa8, 0xf8, 0xda, 0x0a, 0xeb, 0xc8, 0x53, 0x38, 0x14, 0x72, 0x83, 0x46, 0xc9, 0xb5,
	0x90, 0xae, 0x8c, 0xcc, 0x77, 0x46, 0xea, 0x15, 0xff, 0xf3, 0xc0, 0x4c, 0x48, 0x84, 0x07, 0x16,
	0x6e, 0x60, 0x16, 0xb5, 0x73, 0x77, 0xf1, 0xe2, 0xd3, 0xb2, 0x41, 0x77, 0xd3, 0x56, 0x45, 0xad,
	0xd6, 0xcb, 0x9e, 0xee, 0x39, 0xaa, 0xa1, 0xf6, 0xa4, 0xc3, 0x9f, 0x53, 0xdd, 0xf2, 0xc2, 0xd9,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x73, 0x6c, 0x90, 0x57, 0x03, 0x00, 0x00,
}
